version: "0.1.0"
services:
  marketing-website:
    build:
      context: ./
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: sync
          path: ./
          target: /usr/src/app
          ignore:
            - src
            - node_modules
            - .git
            - .gitignore
            - .next
